=== OscarFreij/console_library_system/Console_Library_System/bin/Debug/Config/LibValidationSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://www.w3schools.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="books">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="book" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="title"/>
                    <xs:element type="xs:integer" name="author"/>
                    <xs:element type="xs:string" name="state"/>
                    <xs:element type="xs:integer" name="reads"/>
                  </xs:sequence>
                  <xs:attribute type="xs:integer" name="id" use="required"/>
                  <xs:attribute type="xs:string" name="type"/>
                  <xs:attribute type="xs:string" name="ISBN"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="authors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="firstname"/>
                    <xs:element type="xs:string" name="sirname"/>
                  </xs:sequence>
                  <xs:attribute type="xs:integer" name="id" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="config">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="nextBookId"/>
              <xs:element type="xs:integer" name="nextAuthorId"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== OscarFreij/console_library_system/Console_Library_System/bin/Debug/Collections/Lib1.xml
<?xml version="1.0" encoding="utf-8"?>
<library xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ../Config/LibValidationSchema.xsd">
  <books>
    <book id="0" type="manga" ISBN="">
      <title>A Certain Scientific Railgun Vol.2</title>
      <author>0</author>
      <state>Reading</state>
      <reads>0</reads>
    </book>
  </books>
  <authors>
    <author id="0">
      <firstname>Kazuma</firstname>
      <sirname>Kamachi</sirname>
    </author>
  </authors>
  <config>
    <nextBookId>1</nextBookId>
    <nextAuthorId>1</nextAuthorId>
  </config>
</library>
